[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "financial-data-analysis"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.0.0",
    "psycopg2-binary>=2.9.0",
    "pymupdf>=1.22.0",
    "pytesseract>=0.3.10",
    "pdf2image>=1.16.0",
    "borb>=3.0.0",
    "python-dotenv>=1.0.0"
]

[tool.poetry]
package-mode = false
