# config/observations.yaml
# Defines the universe of observations your engine can make.
# Each observation type has:
#  • id: unique identifier
#  • name: internal code
#  • description: what it measures
#  • formula: textual or code reference describing calculation
#  • params: any parameters (e.g., lookback periods, reference types)
#  • materiality: default threshold for “material” significance

# Use these definitions in your engine to generate observations dynamically,
# ranking them by |value| > materiality threshold and by magnitude.

# ID ranges 20001–29999 reserved for observations

# config/observations.yaml
# =============================================================================
# PURPOSE:
# Defines the universe of financial observations that can trigger board-level 
# questions. Each observation type represents a specific analytical calculation
# that may warrant management attention when it exceeds materiality thresholds.
#
# USAGE:
# - Used by questions_generator.py to compute observations on derived_metrics
# - Linked to questions.yaml via observation_id foreign keys
# - Materiality thresholds determine which observations trigger questions
# - All business logic for scoring and ranking observations lives here
#
# MAINTAINERS: Edit this file for all observation logic changes!
# =============================================================================

metadata:
  version: "2.1"
  description: "Financial metrics observations for board-level question generation"
  default_materiality_threshold: 0.05  # 5% threshold for financial significance
  timestamp: "2025-08-18T19:16:00Z"
  author: "Financial Analytics Engine"

  # Global processing configuration
  processing_rules:
    min_periods_required: 2            # Need at least 2 periods for comparison
    outlier_detection_factor: 3.0      # Values >3x std dev flagged as outliers  
    confidence_threshold: 0.80         # Minimum confidence for observation validity

  # Materiality thresholds by metric type (override default_materiality_threshold)
  materiality_by_metric:
    revenue: 0.03                      # 3% threshold for revenue observations
    gross_profit: 0.04                 # 4% threshold for gross profit  
    ebitda: 0.06                       # 6% threshold for EBITDA

  # Scoring weights for observation importance ranking
  importance_weights:
    growth_metrics: 1.0                # Highest priority for growth analysis
    variance_metrics: 0.9              # High priority for budget/forecast variance
    trend_metrics: 0.7                 # Medium priority for trend analysis
    absolute_metrics: 0.5              # Lower priority for absolute values
    ratio_metrics: 0.8                 # High priority for efficiency ratios

# ID ranges: 20001-29999 reserved for observations
observations:
  # =============================================================================
  # GROWTH & VARIANCE OBSERVATIONS (20001-20010)
  # =============================================================================

  - id: 20001
    name: "growth_mom"
    description: "Month-over-Month growth rate calculation"
    formula: "(current_period - prior_month) / prior_month"
    params:
      lookback_periods: 1
      period_type: "monthly"
      value_types: ["actual"]
      calculation_type: "MoM Growth"
    materiality: null  # Use default_materiality_threshold (5%)

  - id: 20002  
    name: "growth_qoq"
    description: "Quarter-over-Quarter growth rate calculation"
    formula: "(current_period - prior_quarter) / prior_quarter"
    params:
      lookback_periods: 1
      period_type: "quarterly" 
      value_types: ["actual"]
      calculation_type: "QoQ Growth"
    materiality: null  # Use default_materiality_threshold (5%)

  - id: 20003
    name: "growth_yoy" 
    description: "Year-over-Year growth rate calculation"
    formula: "(current_period - prior_year) / prior_year"
    params:
      lookback_periods: 1
      period_type: "yearly"
      value_types: ["actual"]
      calculation_type: "YoY Growth"
    materiality: null  # Use default_materiality_threshold (5%)

  - id: 20004
    name: "variance_vs_budget"
    description: "Variance against budget for same period"
    formula: "(actual_value - budget_value) / budget_value"
    params:
      comparison_type: "budget"
      value_types: ["actual", "budget"]
      calculation_type: "Variance vs Budget"
    materiality: 0.03  # 3% threshold for budget variances (more sensitive)

  - id: 20005
    name: "variance_vs_forecast"
    description: "Variance against forecast for same period" 
    formula: "(actual_value - forecast_value) / forecast_value"
    params:
      comparison_type: "forecast"
      value_types: ["actual", "forecast"]
      calculation_type: "Variance vs Forecast"
    materiality: null  # Use default_materiality_threshold (5%)

  - id: 20006
    name: "ytd_performance"
    description: "Year-to-Date performance vs prior year"
    formula: "(ytd_current - ytd_prior_year) / ytd_prior_year" 
    params:
      aggregation_type: "ytd"
      comparison_period: "prior_year"
      calculation_type: "YTD Growth"
    materiality: null  # Use default_materiality_threshold (5%)

  # =============================================================================
  # TREND & PATTERN OBSERVATIONS (20007-20015)
  # =============================================================================

  - id: 20007
    name: "trend_direction"
    description: "Multi-period trend direction analysis"
    formula: "linear_regression_slope(values[-6:])"
    params:
      window_periods: 6
      trend_sensitivity: 0.02
      calculation_type: "Trend Analysis"
    materiality: 0.02  # 2% threshold for trend detection (more sensitive)

  - id: 20008
    name: "volatility_measure"
    description: "Standard deviation of recent periods"
    formula: "stdev(values[-6:])"
    params:
      window_periods: 6  
      volatility_threshold: 0.15
      calculation_type: "Volatility Analysis"
    materiality: null  # Use default_materiality_threshold (5%)

  - id: 20009
    name: "seasonal_variance"
    description: "Deviation from seasonal pattern"
    formula: "(current - seasonal_average) / seasonal_average"
    params:
      seasonal_periods: 12
      seasonal_lookback: 3
      calculation_type: "Seasonal Analysis"
    materiality: null  # Use default_materiality_threshold (5%)

  # =============================================================================
  # ABSOLUTE VALUE OBSERVATIONS (20010-20015)
  # =============================================================================

  - id: 20010
    name: "absolute_change"
    description: "Absolute dollar/unit change from prior period"
    formula: "current_period - prior_period"
    params:
      change_type: "absolute"
      calculation_type: "Absolute Change"
    materiality: null  # Use default_materiality_threshold (5%)

  - id: 20011
    name: "magnitude_check"
    description: "Unusual magnitude relative to historical range"
    formula: "(current - historical_mean) / historical_stdev"
    params:
      historical_periods: 12
      outlier_threshold: 2.0
      calculation_type: "Magnitude Analysis"
    materiality: null  # Use default_materiality_threshold (5%)

  # =============================================================================
  # PERFORMANCE RATIO OBSERVATIONS (20012-20015)
  # =============================================================================

  - id: 20012
    name: "efficiency_ratio"
    description: "Performance efficiency metrics"
    formula: "dependent_metric / independent_metric"
    params:
      ratio_type: "efficiency"
      valid_denominators: ["revenue", "assets", "employees"]
      calculation_type: "Efficiency Analysis"
    materiality: null  # Use default_materiality_threshold (5%)

  - id: 20013
    name: "margin_analysis" 
    description: "Profit margin progression analysis"
    formula: "profit_metric / revenue_metric"
    params:
      margin_type: ["gross", "operating", "net"]
      benchmark_comparison: true
      calculation_type: "Margin Analysis"
    materiality: null  # Use default_materiality_threshold (5%)

# =============================================================================
# END OF FILE
# - To extend: add new observations with IDs in 20016-29999 range
# - All observation changes here flow through to questions_generator.py
# - Link new observations to questions via observation_id in questions.yaml
# =============================================================================
