# config/periods.yaml - CONSOLIDATED SINGLE SOURCE OF TRUTH (ISO 8601 Edition)
# Replaces scattered period logic across multiple files
# Aligned with ISO 8601 period seeding in tables.yaml

metadata:
  version: "3.0"
  description: "Complete period handling configuration - ISO 8601 compliant"
  author: "Financial Analytics Engine"
  timestamp: "2025-08-21T14:30:00Z"
  iso_compliant: true

# =============================================================================
# CANONICAL PERIOD DEFINITIONS (ISO 8601 FORMAT - matches tables.yaml seed)
# =============================================================================
canonical_formats:
  monthly: "YYYY-MM"        # 2025-02 (ISO 8601)
  quarterly: "YYYY-QN"      # 2025-Q1 (ISO 8601 with quarters)
  yearly: "YYYY"            # 2025 (ISO 8601)

# =============================================================================
# COMPREHENSIVE ALIAS MAPPING - All possible input variants → ISO canonical
# =============================================================================
period_aliases:
  # February 2025 canonical mappings → 2025-02
  "2025-02":
    canonical: "2025-02"
    period_type: "Monthly"
    start_date: "2025-02-01"
    end_date: "2025-02-28"
    aliases:
      - "2025-02"           # ISO format (direct)
      - "Feb 2025"          # Business format
      - "February 2025"     # Full month name
      - "02/2025"           # US format
      - "2025/02"           # Alternative slash
      - "Feb-2025"          # Hyphenated
      - "Feb '25"           # Abbreviated year with quote
      - "F25"               # Ultra short
      - "2/25"              # Short slash
      - "2025.02"           # Dotted format
      - "February Twenty Twenty-Five"  # Written out
      - "2025 Feb"          # Reversed
      - "25-Feb"            # Short year first

  # January 2025 → 2025-01
  "2025-01":
    canonical: "2025-01"
    period_type: "Monthly"
    start_date: "2025-01-01"
    end_date: "2025-01-31"
    aliases:
      - "2025-01"
      - "Jan 2025"
      - "January 2025"
      - "01/2025"
      - "2025/01"
      - "Jan-2025"
      - "Jan '25"
      - "J25"
      - "1/25"
      - "2025.01"

  # March 2025 → 2025-03
  "2025-03":
    canonical: "2025-03"
    period_type: "Monthly"
    start_date: "2025-03-01"
    end_date: "2025-03-31"
    aliases:
      - "2025-03"
      - "Mar 2025"
      - "March 2025"
      - "03/2025"
      - "2025/03"
      - "Mar-2025"
      - "Mar '25"
      - "M25"
      - "3/25"

  # April 2025 → 2025-04
  "2025-04":
    canonical: "2025-04"
    period_type: "Monthly"
    start_date: "2025-04-01"
    end_date: "2025-04-30"
    aliases:
      - "2025-04"
      - "Apr 2025"
      - "April 2025"
      - "04/2025"
      - "2025/04"
      - "Apr-2025"
      - "Apr '25"
      - "A25"
      - "4/25"

  # May 2025 → 2025-05
  "2025-05":
    canonical: "2025-05"
    period_type: "Monthly"
    start_date: "2025-05-01"
    end_date: "2025-05-31"
    aliases:
      - "2025-05"
      - "May 2025"
      - "05/2025"
      - "2025/05"
      - "May-2025"
      - "May '25"
      - "5/25"

  # June 2025 → 2025-06
  "2025-06":
    canonical: "2025-06"
    period_type: "Monthly"
    start_date: "2025-06-01"
    end_date: "2025-06-30"
    aliases:
      - "2025-06"
      - "Jun 2025"
      - "June 2025"
      - "06/2025"
      - "2025/06"
      - "Jun-2025"
      - "Jun '25"
      - "6/25"

  # July 2025 → 2025-07
  "2025-07":
    canonical: "2025-07"
    period_type: "Monthly"
    start_date: "2025-07-01"
    end_date: "2025-07-31"
    aliases:
      - "2025-07"
      - "Jul 2025"
      - "July 2025"
      - "07/2025"
      - "2025/07"
      - "Jul-2025"
      - "Jul '25"
      - "7/25"

  # August 2025 → 2025-08
  "2025-08":
    canonical: "2025-08"
    period_type: "Monthly"
    start_date: "2025-08-01"
    end_date: "2025-08-31"
    aliases:
      - "2025-08"
      - "Aug 2025"
      - "August 2025"
      - "08/2025"
      - "2025/08"
      - "Aug-2025"
      - "Aug '25"
      - "8/25"

  # September 2025 → 2025-09
  "2025-09":
    canonical: "2025-09"
    period_type: "Monthly"
    start_date: "2025-09-01"
    end_date: "2025-09-30"
    aliases:
      - "2025-09"
      - "Sep 2025"
      - "September 2025"
      - "Sept 2025"
      - "09/2025"
      - "2025/09"
      - "Sep-2025"
      - "Sep '25"
      - "9/25"

  # October 2025 → 2025-10
  "2025-10":
    canonical: "2025-10"
    period_type: "Monthly"
    start_date: "2025-10-01"
    end_date: "2025-10-31"
    aliases:
      - "2025-10"
      - "Oct 2025"
      - "October 2025"
      - "10/2025"
      - "2025/10"
      - "Oct-2025"
      - "Oct '25"
      - "O25"

  # November 2025 → 2025-11
  "2025-11":
    canonical: "2025-11"
    period_type: "Monthly"
    start_date: "2025-11-01"
    end_date: "2025-11-30"
    aliases:
      - "2025-11"
      - "Nov 2025"
      - "November 2025"
      - "11/2025"
      - "2025/11"
      - "Nov-2025"
      - "Nov '25"
      - "N25"

  # December 2025 → 2025-12
  "2025-12":
    canonical: "2025-12"
    period_type: "Monthly"
    start_date: "2025-12-01"
    end_date: "2025-12-31"
    aliases:
      - "2025-12"
      - "Dec 2025"
      - "December 2025"
      - "12/2025"
      - "2025/12"
      - "Dec-2025"
      - "Dec '25"
      - "D25"

  # Q1 2025 canonical mappings → 2025-Q1
  "2025-Q1":
    canonical: "2025-Q1"
    period_type: "Quarterly"
    start_date: "2025-01-01"
    end_date: "2025-03-31"
    aliases:
      - "2025-Q1"          # ISO format (direct)
      - "Q1 2025"          # Business format
      - "2025 Q1"          # Alternative order
      - "First Quarter 2025"
      - "1Q25"             # Short format
      - "Q1'25"            # Quote format
      - "Jan-Mar 2025"     # Month range
      - "2025 Q1 (Jan-Mar)"
      - "Quarter 1, 2025"
      - "FY25 Q1"          # Fiscal reference
      - "2025 First Quarter"

  # Q2 2025 → 2025-Q2
  "2025-Q2":
    canonical: "2025-Q2"
    period_type: "Quarterly"
    start_date: "2025-04-01"
    end_date: "2025-06-30"
    aliases:
      - "2025-Q2"
      - "Q2 2025"
      - "2025 Q2"
      - "Second Quarter 2025"
      - "2Q25"
      - "Q2'25"
      - "Apr-Jun 2025"
      - "Quarter 2, 2025"

  # Q3 2025 → 2025-Q3
  "2025-Q3":
    canonical: "2025-Q3"
    period_type: "Quarterly"
    start_date: "2025-07-01"
    end_date: "2025-09-30"
    aliases:
      - "2025-Q3"
      - "Q3 2025"
      - "2025 Q3"
      - "Third Quarter 2025"
      - "3Q25"
      - "Q3'25"
      - "Jul-Sep 2025"

  # Q4 2025 → 2025-Q4
  "2025-Q4":
    canonical: "2025-Q4"
    period_type: "Quarterly"
    start_date: "2025-10-01"
    end_date: "2025-12-31"
    aliases:
      - "2025-Q4"
      - "Q4 2025"
      - "2025 Q4"
      - "Fourth Quarter 2025"
      - "4Q25"
      - "Q4'25"
      - "Oct-Dec 2025"

  # 2025 yearly → 2025
  "2025":
    canonical: "2025"
    period_type: "Yearly"
    start_date: "2025-01-01"
    end_date: "2025-12-31"
    aliases:
      - "2025"             # ISO format (direct)
      - "FY25"             # Fiscal year short
      - "FY 2025"          # Fiscal year full
      - "Year 2025"        # Descriptive
      - "CY25"             # Calendar year short
      - "Calendar 2025"    # Calendar year full
      - "'25"              # Quote abbreviated

  # 2024 periods for historical data
  "2024-12":
    canonical: "2024-12"
    period_type: "Monthly"
    start_date: "2024-12-01"
    end_date: "2024-12-31"
    aliases:
      - "2024-12"
      - "Dec 2024"
      - "December 2024"
      - "12/2024"
      - "2024/12"

  "2024-Q4":
    canonical: "2024-Q4"
    period_type: "Quarterly"
    start_date: "2024-10-01"
    end_date: "2024-12-31"
    aliases:
      - "2024-Q4"
      - "Q4 2024"
      - "2024 Q4"
      - "4Q24"

  "2024":
    canonical: "2024"
    period_type: "Yearly"
    start_date: "2024-01-01"
    end_date: "2024-12-31"
    aliases:
      - "2024"
      - "FY24"
      - "FY 2024"
      - "Year 2024"
      - "CY24"
      - "'24"

# =============================================================================
# PARSING CONFIGURATION
# =============================================================================
parsing:
  # Multi-stage normalization pipeline
  cleaning_rules:
    - remove_prefixes: ["period:", "pd:", "time:"]
    - normalize_whitespace: true
    - normalize_punctuation: {"–": "-", "—": "-"}
    - case_sensitivity: false
    
  # Regex patterns for fuzzy matching (fallback when direct alias fails)
  patterns:
    monthly_patterns:
      - pattern: "(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec|january|february|march|april|may|june|july|august|september|october|november|december)\\s*[\\-\\s]*(\\d{2,4})"
        canonical_format: "YYYY-MM"
      - pattern: "(\\d{1,2})/(\\d{4})"
        canonical_format: "YYYY-MM"
        
    quarterly_patterns:
      - pattern: "(q[1-4]|quarter\\s*[1-4]|[1-4]q)\\s*[\\-\\s]*(\\d{2,4})"
        canonical_format: "YYYY-QN"
        
    yearly_patterns:
      - pattern: "(fy|fiscal\\s*year)\\s*(\\d{2,4})"
        canonical_format: "YYYY"
      - pattern: "^(\\d{4})$"
        canonical_format: "YYYY"

# =============================================================================
# VALIDATION & ERROR HANDLING
# =============================================================================
validation:
  max_future_years: 20
  max_past_years: 50
  require_year: true
  strict_mode: false  # If true, unknown periods cause errors vs warnings

error_handling:
  unknown_period_action: "log_and_continue"  # vs "raise_error"
  default_fallback:
    type: "Monthly"
    label: "Unknown Period"
    use_current_date: true

# =============================================================================
# DATABASE INTEGRATION (matches tables.yaml seed output exactly)
# =============================================================================
database_mapping:
  # Expected database period_label formats from tables.yaml seed
  expected_db_formats:
    monthly: "YYYY-MM"        # 2025-02
    quarterly: "YYYY-QN"      # 2025-Q1  
    yearly: "YYYY"            # 2025

  # Period creation template for missing periods
  period_creation_template:
    monthly:
      period_label_format: "YYYY-MM"
      start_date_calc: "date_trunc('month', '{year}-{month:02d}-01'::date)"
      end_date_calc: "date_trunc('month', '{year}-{month:02d}-01'::date) + INTERVAL '1 month' - INTERVAL '1 day'"
    quarterly:
      period_label_format: "YYYY-QN"
      start_date_calc: "date_trunc('quarter', '{year}-{quarter_start_month:02d}-01'::date)"
      end_date_calc: "date_trunc('quarter', '{year}-{quarter_start_month:02d}-01'::date) + INTERVAL '3 months' - INTERVAL '1 day'"
    yearly:
      period_label_format: "YYYY"
      start_date_calc: "'{year}-01-01'::date"
      end_date_calc: "'{year}-12-31'::date"

# =============================================================================
# FISCAL YEAR CONFIGURATION
# =============================================================================
fiscal_settings:
  fiscal_year_end: "12-31"  # December 31st
  fiscal_quarter_start: "01-01"  # Q1 starts January 1st
  
# =============================================================================
# INGESTION PIPELINE INTEGRATION
# =============================================================================
ingestion_hooks:
  # How this config integrates with your ingester
  pre_normalization: "apply_cleaning_rules"
  lookup_strategy: "direct_alias_first_then_pattern_match"
  post_resolution: "validate_canonical_exists_in_db"
  error_logging: "log_unresolved_periods_for_review"
  period_creation: "upsert_missing_periods_with_iso_format"

# =============================================================================
# AUTO-GENERATION RULES (for programmatic alias creation)
# =============================================================================
generation_rules:
  # Automatically generate common variants for new canonical periods
  auto_generate_variants:
    enabled: true
    patterns:
      monthly:
        - "{year}-{month:02d}"          # 2025-02 (ISO)
        - "{month_name} {year}"         # February 2025
        - "{month_abbr} {year}"         # Feb 2025
        - "{month:02d}/{year}"          # 02/2025
        - "{year}/{month:02d}"          # 2025/02
        - "{month_abbr}-{year_short}"   # Feb-25
      quarterly:
        - "{year}-Q{quarter}"           # 2025-Q1 (ISO)
        - "Q{quarter} {year}"           # Q1 2025
        - "{year} Q{quarter}"           # 2025 Q1
        - "{quarter}Q{year_short}"      # 1Q25
      yearly:
        - "{year}"                      # 2025 (ISO)
        - "FY{year_short}"             # FY25
        - "FY {year}"                  # FY 2025

# =============================================================================
# MIGRATION NOTES
# =============================================================================
migration_notes:
  from_business_format: |
    If migrating from business formats ("Feb 2025", "Q1 2025"):
    1. Update tables.yaml seed SQL to use ISO formats
    2. Run schema regeneration to create ISO periods
    3. Update existing data with migration script
    4. All new ingestion will use ISO canonical format
  
  breaking_changes:
    - "period_label format changed from 'Feb 2025' to '2025-02'"
    - "period_label format changed from 'Q1 2025' to '2025-Q1'"
    - "Existing queries referencing old format will break"
    - "Analytics and reports need period_label updates"

# =============================================================================
# CLEANUP INSTRUCTIONS
# =============================================================================
cleanup_required:
  remove_from_files:
    fields_yaml:
      - "date_formats section (lines 245-252)"
      - "period_types section (lines 254-258)"
      - "auto_create_periods section (lines 260-263)"
    periods_yaml:
      - "Replace entire file with this consolidated version"
  
  reason: "Eliminates duplication and centralizes all period logic"