# config/tables.yaml

tables:
  # 1. Reference data
  - name: companies
    columns:
      - name: id
        type: SERIAL
        constraints:
          - PRIMARY KEY
      - name: name
        type: TEXT
        constraints:
          - NOT NULL
      - name: industry
        type: TEXT
      - name: created_at
        type: TIMESTAMP
        default: NOW()
        constraints:
          - NOT NULL
      - name: updated_at
        type: TIMESTAMP
        default: NOW()
        constraints:
          - NOT NULL
    unique_constraints:
      - [name]
    seed:
      - |
        INSERT INTO companies (id, name, industry)
        VALUES (99, 'Example Company', 'Example Industry')
        ON CONFLICT (name) DO NOTHING;

  - name: periods
    columns:
      - name: id
        type: SERIAL
        constraints:
          - PRIMARY KEY
      - name: period_type
        type: TEXT
        constraints:
          - NOT NULL
      - name: period_label
        type: TEXT
        constraints:
          - NOT NULL
      - name: start_date
        type: DATE
      - name: end_date
        type: DATE
      - name: created_at
        type: TIMESTAMP
        default: NOW()
        constraints:
          - NOT NULL
      - name: updated_at
        type: TIMESTAMP
        default: NOW()
        constraints:
          - NOT NULL
    unique_constraints:
      - [period_label, period_type]

  # 2. Ingestion tables
  - name: line_item_definitions
    columns:
      - name: id
        type: INT
        constraints:
          - PRIMARY KEY
      - name: name
        type: TEXT
        constraints:
          - NOT NULL
      - name: aliases
        type: TEXT[]
      - name: description
        type: TEXT
    unique_constraints:
      - [name]

  - name: financial_metrics
    columns:
      - name: company_id
        type: INT
        constraints:
          - NOT NULL
      - name: line_item
        type: TEXT
        constraints:
          - NOT NULL
      - name: period_label
        type: TEXT
        constraints:
          - NOT NULL
      - name: value
        type: NUMERIC
      - name: value_type
        type: TEXT
      - name: frequency
        type: TEXT
      - name: currency
        type: TEXT
      - name: source_file
        type: TEXT
      - name: source_page
        type: INT
      - name: notes
        type: TEXT
    primary_key:
      - company_id
      - line_item
      - period_label
      - value

  # 3. Derived metrics
  - name: derived_metrics
    columns:
      - name: id
        type: SERIAL
        constraints:
          - PRIMARY KEY
      - name: base_metric_id
        type: INT
        constraints:
          - NOT NULL
      - name: calculation_type
        type: TEXT
      - name: company_id
        type: INT
        constraints:
          - NOT NULL
      - name: period_label
        type: TEXT
        constraints:
          - NOT NULL
      - name: calculated_value
        type: NUMERIC
      - name: unit
        type: TEXT
      - name: source_ids
        type: TEXT
      - name: calculation_note
        type: TEXT
      - name: corroboration_status
        type: TEXT
      - name: created_at
        type: TIMESTAMP
        default: NOW()
        constraints:
          - NOT NULL
      - name: updated_at
        type: TIMESTAMP
        default: NOW()
        constraints:
          - NOT NULL
    unique_constraints:
      - [base_metric_id, company_id, period_label, calculation_type]

  # 4. Question engine tables
  - name: question_templates
    columns:
      - name: id
        type: SERIAL
        constraints:
          - PRIMARY KEY
      - name: line_item
        type: TEXT
      - name: template
        type: TEXT

  - name: questions
    columns:
      - name: id
        type: SERIAL
        constraints:
          - PRIMARY KEY
      - name: company_id
        type: INT
      - name: period_label
        type: TEXT
      - name: line_item
        type: TEXT
      - name: question_template_id
        type: INT
      - name: generated_at
        type: TIMESTAMP
        default: NOW()

  # 5. Optional reporting tables
  - name: live_questions
    columns:
      - name: id
        type: SERIAL
        constraints:
          - PRIMARY KEY
      - name: derived_metric_id
        type: INT
      - name: status
        type: TEXT
      - name: created_at
        type: TIMESTAMP
        default: NOW()
      - name: updated_at
        type: TIMESTAMP
        default: NOW()

  - name: question_logs
    columns:
      - name: id
        type: SERIAL
        constraints:
          - PRIMARY KEY
      - name: live_question_id
        type: INT
      - name: changed_on
        type: TIMESTAMP
        default: NOW()

  - name: generated_reports
    columns:
      - name: id
        type: SERIAL
        constraints:
          - PRIMARY KEY
      - name: generated_on
        type: TIMESTAMP
        default: NOW()
      - name: company_id
        type: INT
      - name: filter_type
        type: TEXT
      - name: report_file_path
        type: TEXT
