-- Auto-generated by scripts/generate_questions.py
-- Generated from: /Users/a/repo/financial-data-analysis/config/questions.yaml
-- Version: 2.1
-- Description: Question templates for board-level financial analysis
-- Timestamp: 2025-08-18T19:16:00Z

-- =============================================
-- Question Templates Table
-- =============================================

-- Drop existing table and dependencies
DROP TABLE IF EXISTS question_templates CASCADE;

-- Create question_templates table with full schema
CREATE TABLE question_templates (
    id INTEGER PRIMARY KEY,
    observation_id INTEGER NOT NULL,
    importance INTEGER NOT NULL DEFAULT 1,
    category TEXT NOT NULL DEFAULT 'general',
    priority TEXT NOT NULL DEFAULT 'medium',
    template TEXT NOT NULL,
    weight NUMERIC DEFAULT 1.0,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_question_templates_observation_id ON question_templates(observation_id);
CREATE INDEX IF NOT EXISTS idx_question_templates_category ON question_templates(category);
CREATE INDEX IF NOT EXISTS idx_question_templates_priority ON question_templates(priority);
CREATE INDEX IF NOT EXISTS idx_question_templates_importance ON question_templates(importance DESC);

-- Insert question templates
INSERT INTO question_templates (
    id, observation_id, importance, category, priority, template, weight, metadata
) VALUES
    (30001, 20001, 5, 'growth_analysis', 'high', '{{ metric_name }} changed {{ percent(current_value, prior_month_value) }}% month-over-month ({{ format_currency(current_value) }} vs {{ format_currency(prior_month_value) }}). What operational factors drove this {{ conditional(current_value > prior_month_value, "growth", "decline") }}?', 1.0, '{}'::jsonb),
    (30002, 20002, 4, 'growth_analysis', 'high', '{{ metric_name }} showed {{ percent(current_value, prior_quarter_value) }}% growth quarter-over-quarter. How does this align with our quarterly targets and strategic initiatives?', 1.0, '{}'::jsonb),
    (30003, 20003, 5, 'growth_analysis', 'high', 'Year-over-year {{ metric_name }} {{ conditional(current_value > prior_year_value, "increased", "decreased") }} by {{ percent(current_value, prior_year_value) }}% ({{ format_abs(current_value - prior_year_value) }}). What strategic initiatives contributed to this performance?', 1.2, '{}'::jsonb),
    (30004, 20006, 4, 'growth_analysis', 'high', 'Year-to-date {{ metric_name }} is {{ percent(ytd_current, ytd_prior) }}% {{ conditional(ytd_current > ytd_prior, "ahead of", "behind") }} last year. Are we on track for annual targets?', 1.0, '{}'::jsonb),
    (30011, 20004, 5, 'variance_analysis', 'high', '{{ metric_name }} is {{ percent(current_value, budget_value) }}% {{ conditional(current_value > budget_value, "above", "below") }} budget ({{ format_currency(current_value) }} vs {{ format_currency(budget_value) }}). What explains this variance and what actions are required?', 1.3, '{}'::jsonb),
    (30012, 20004, 5, 'variance_analysis', 'high', '🚨 CRITICAL: {{ metric_name }} variance of {{ percent(current_value, budget_value) }}% impacts {{ format_currency(abs(current_value - budget_value)) }}. What immediate corrective actions are required?', 1.5, '{}'::jsonb),
    (30013, 20005, 4, 'variance_analysis', 'high', '{{ metric_name }} came in {{ percent(current_value, forecast_value) }}% {{ conditional(current_value > forecast_value, "higher", "lower") }} than forecast. Should we adjust our forecasting methodology or expectations?', 1.0, '{}'::jsonb),
    (30021, 20007, 3, 'trend_pattern', 'high', '{{ metric_name }} shows a {{ conditional(trend_slope > 0, "positive", "negative") }} trend over the past {{ trend_periods }} periods. Is this trend sustainable and aligned with our strategic direction?', 0.9, '{}'::jsonb),
    (30022, 20008, 2, 'trend_pattern', 'high', '{{ metric_name }} volatility is {{ round_smart(volatility * 100, 1) }}%. What factors are driving this variability and how can we improve predictability?', 0.8, '{}'::jsonb),
    (30023, 20009, 3, 'trend_pattern', 'high', '{{ metric_name }} is {{ percent(current_value, seasonal_average) }}% {{ conditional(current_value > seasonal_average, "above", "below") }} seasonal norm. What changed our typical seasonal patterns?', 0.9, '{}'::jsonb),
    (30031, 20010, 2, 'absolute_magnitude', 'high', 'Absolute change in {{ metric_name }} was {{ format_currency(absolute_change) }}. Is this magnitude significant relative to our scale of operations?', 0.7, '{}'::jsonb),
    (30032, 20011, 3, 'absolute_magnitude', 'high', '{{ metric_name }} is {{ round_smart(z_score, 1) }} standard deviations {{ conditional(z_score > 0, "above", "below") }} its historical mean. Should this outlier be investigated further?', 0.8, '{}'::jsonb),
    (30041, 20012, 3, 'ratio_efficiency', 'high', '{{ ratio_name }} ratio is {{ round_smart(ratio_value, 2) }}, {{ conditional(ratio_trend > 0, "improving", "declining") }} from prior periods. How does this impact our operational efficiency targets?', 0.9, '{}'::jsonb),
    (30042, 20013, 4, 'ratio_efficiency', 'high', '{{ metric_name }} margin is {{ round_smart(margin_percentage * 100, 1) }}%, {{ conditional(margin_change > 0, "up", "down") }} {{ round_smart(abs(margin_change) * 100, 1) }}% points. How does this compare to industry benchmarks and competitors?', 1.1, '{}'::jsonb),
    (30051, 20001, 4, 'growth_analysis', 'high', 'Monthly {{ metric_name }} performance shows {{ percent(current_value, prior_month_value) }}% change. What specific business drivers contributed to this result?', 0.9, '{}'::jsonb),
    (30052, 20003, 4, 'growth_analysis', 'high', 'Annual {{ metric_name }} growth of {{ percent(current_value, prior_year_value) }}% represents {{ format_currency(current_value - prior_year_value) }} impact. How does this position us for next year''s planning?', 1.0, '{}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
    observation_id = EXCLUDED.observation_id,
    importance = EXCLUDED.importance,
    category = EXCLUDED.category,
    priority = EXCLUDED.priority,
    template = EXCLUDED.template,
    weight = EXCLUDED.weight,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

-- =============================================
-- Configuration Storage Table
-- =============================================

-- Create configuration table if not exists
CREATE TABLE IF NOT EXISTS question_generation_config (
    id SERIAL PRIMARY KEY,
    config_key TEXT NOT NULL UNIQUE,
    config_value JSONB NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Insert configuration data
INSERT INTO question_generation_config (config_key, config_value, description) VALUES
    ('rendering_helpers', '["percent(current, prior): Calculate percentage change", "format_currency(value): Format as currency with symbols", "format_abs(value): Format absolute values with +/- indicators", "round_smart(value, decimals): Smart rounding based on magnitude", "conditional(condition, true_text, false_text): Conditional text"]'::jsonb, 'Available template rendering functions'),
    ('selection_logic', '["1. Calculate all observations from observations.yaml", "2. Filter observations where |value| >= materiality_threshold", "3. Join observations with questions by observation_id", "4. Rank by importance (desc) then observation magnitude (desc)", "5. Render templates with observation context + metric data", "6. Return top N questions based on board meeting requirements"]'::jsonb, 'Question selection and ranking logic'),
    ('metadata', '{"version": "2.1", "description": "Question templates for board-level financial analysis", "default_question_weight": 1.0, "timestamp": "2025-08-18T19:16:00Z", "author": "Financial Analytics Engine"}'::jsonb, 'Question template metadata and configuration')
ON CONFLICT (config_key) DO UPDATE SET
    config_value = EXCLUDED.config_value,
    description = EXCLUDED.description,
    updated_at = NOW();

-- =============================================
-- Generation Summary
-- =============================================

-- Generated 16 question templates
-- Categories: absolute_magnitude, growth_analysis, ratio_efficiency, trend_pattern, variance_analysis
-- Priority distribution: {'high': 16}
-- Importance range: 2-5
-- Linked observations: [20001, 20002, 20003, 20004, 20005, 20006, 20007, 20008, 20009, 20010, 20011, 20012, 20013]

-- Schema generation completed successfully
