-- Auto-generated by generate_questions.py

DROP TABLE IF EXISTS question_templates CASCADE;

CREATE TABLE IF NOT EXISTS question_templates (
  id INT PRIMARY KEY,
  observation_id INT NOT NULL,
  importance INT NOT NULL,
  template TEXT NOT NULL
);

-- Seed question_templates
INSERT INTO question_templates (id, observation_id, importance, template) VALUES
  (30001, 20001, 3, 'The {{ metric }} grew by {{ percent(current, prior_month) }}% month-over-month. What underlying factors drove this growth?
'),
  (30002, 20002, 2, '{{ metric }} changed by {{ percent(current, prior_quarter) }}% quarter-over-quarter. Which operational changes contributed to this movement?
'),
  (30003, 20003, 4, 'Year-over-year {{ metric }} increased by {{ percent(current, prior_year) }}%. How does this performance align with strategic goals?
'),
  (30004, 20004, 5, '{{ metric }} is {{ percent(current, budget) }}% {{ if current > budget then ''above'' else ''below'' }} budget. What explains this deviation from plan?
'),
  (30005, 20005, 2, '{{ metric }} is {{ percent(current, prior) }}% {{ if current > prior then ''above'' else ''below'' }} the prior period. Are there one-off events or trends affecting this?
'),
  (30006, 20006, 3, 'Year-to-date {{ metric }} performance is {{ percent(ytd_current, ytd_prior) }}% {{ if ytd_current > ytd_prior then ''ahead'' else ''behind'' }} last year. What key drivers impacted YTD results?
'),
  (30007, 20007, 1, 'The absolute change in {{ metric }} from the prior period is {{ format_abs(current - prior) }}. Is this magnitude significant in the broader context?
'),
  (30008, 20008, 1, 'The 3-month moving average of {{ metric }} is {{ round(moving_average,2) }}. Does this trend differ from the immediate period change?
'),
  (30009, 20009, 1, 'The 3-month volatility of {{ metric }} is {{ round(volatility,2) }}. What factors contribute to this variability?
'),
  (30010, 20010, 2, 'The P/E ratio for {{ metric }} is {{ round(pe_ratio,2) }}. How does this compare to industry benchmarks?
')
ON CONFLICT (id) DO NOTHING;
